version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - worktree
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: babel-plugin-preval
    versions:
    - ">= 3.0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: "@date-io/core"
    versions:
    - ">= 0"
  - dependency-name: "@date-io/date-fns"
    versions:
    - ">= 0"
  - dependency-name: jss-*
    versions:
    - ">= 0"
  - dependency-name: next
    versions:
    - 9.x
  - dependency-name: prettier
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: size-limit
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: url-loader
    versions:
    - ">= 3.0"
  - dependency-name: dtslint
    versions:
    - 4.0.4
    - 4.0.6
    - 4.0.7
    - 4.0.8
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
  - dependency-name: temp
    versions:
    - 0.9.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
